name: dinov3
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - antlr-python-runtime=4.9.3
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - comm=0.2.3
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - omegaconf=2.3.0
  - openssl=3.0.18
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - astroid==3.3.11
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - daal==2025.10.0
      - dill==0.4.0
      - docstr-coverage==2.3.2
      - einops==0.8.1
      - filelock==3.20.3
      - flash-attn==2.8.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - ftfy==6.3.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - iopath==0.1.10
      - isort==6.1.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mccabe==0.7.0
      - mpmath==1.3.0
      - mypy==1.17.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - numpy==2.4.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.13.0.90
      - pandas==2.3.3
      - pathspec==1.0.3
      - pillow==12.1.0
      - portalocker==3.2.0
      - pycocotools==2.0.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pylint==3.3.8
      - pyparsing==3.3.2
      - pytz==2025.2
      - regex==2025.11.3
      - requests==2.32.5
      - ruff==0.12.8
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scikit-learn-intelex==2025.10.0
      - scipy==1.17.0
      - simsimd==6.5.12
      - stringzilla==4.6.0
      - submitit==1.5.4
      - sympy==1.14.0
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - tomlkit==0.13.3
      - torch==2.9.1+cu126
      - torchmetrics==1.8.2
      - torchvision==0.24.1+cu126
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.1
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - xformers==0.0.33.post2
prefix: /home/jovyan/.conda/envs/dinov3
